version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - EXECUTION_ENVIRONMENT=DOCKER
    command: bash -c "python speed_checker/core.py run"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition:
          service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/.env

  migrations:
    build:
      context: .
    command: bash -c "python speed_checker/prepare_db.py run"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: resources
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
